apiVersion: v1
kind: Pod
metadata:
  name: ganeshnginx2
  labels: 
    app: ganenginx
spec:
 containers:
   - name: nginxcontainer1
     image: nginx
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginxservice2
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
